### ISSUE TITLE
Kupon Kodu

### ISSUE THREAD

**Issue by ahmetturk93** [taylanbildik/Linux_Dersleri#1]
Hocam selamlar, kupon kodunuzun süresi dolmuş linki güncelleme şansınız var mı? Böyle repoya böyle issue açılır herhâlde :)) saygılar

**Comment by taylanbildik** [comment]
Her ay yalnızca 3 kupon oluşturma imkanım var. Üstelik en iyi fiyat için oluşturulan kupon yalnızca 5 günlük oluyor. 
31 gün süreli olan kuponun fiyat aralığı maalesef daha yüksek ve eğitmen olarak var olan kupon oluşturma politikalarına bağlıyım. Görsele bakacak olursanız, kupon oluşturma politikasını görebilirsiniz. 

![Screenshot_2](https://user-images.githubusercontent.com/34001728/168628440-daee3cb9-c62b-4e5f-9bc7-33dab8e986a1.png)

Yalnızca 5 gün sürecek kupon için uygun zaman aralıklarında güncelleme yapsam bile yine çoğu arkadaş faydalanamayacak. Bunun yerine doğrudan bana udemy veya linkedin üzerinden yazarsanız mümkünse o an değilse de yakın tarihte size uygun kuponu oluşturabilirim.

Vakit ayırıp geri bildirimde bulunduğunuz için teşekkür eder, çalışmalarınızda kolaylıklar dilerim.
